name: Deploy to Fly

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        default: 'access-ui'
        required: true
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
    concurrency: deploy-to-fly-group-${{ inputs.environment }}
    steps:
      - name: Checkout repository
        timeout-minutes: 5
        uses: actions/checkout@v4

      - name: Setup flyctl
        timeout-minutes: 5
        uses: superfly/flyctl-actions/setup-flyctl@1.5
      
      - name: Deploy to Fly
        timeout-minutes: 30
        run: flyctl deploy --remote-only --config fly.${{ inputs.environment }}.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
